import React from 'react';

const Dashboard = () => {
    return (
        <div>
            this is dashboard 
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem error sequi rem accusamus quae? Minima, laboriosam, perspiciatis obcaecati deleniti in dolore beatae unde enim soluta officia quidem voluptatum illo, blanditiis ratione qui! Cupiditate velit hic pariatur veniam fuga sequi corporis sunt aspernatur. Enim accusantium libero earum exercitationem facilis, unde fugiat mollitia cum reprehenderit qui, eveniet dolores voluptatum! Quae laborum inventore amet! Quidem fuga, neque voluptates amet iste non sapiente assumenda error, doloremque asperiores voluptatibus maxime ex magnam ab consectetur debitis id velit ipsa minima nihil, facilis quia optio. Laudantium soluta perferendis laborum ipsa debitis aliquid illo error consequuntur recusandae itaque, eveniet molestias eligendi culpa iure quam dolores architecto? Repudiandae iure tempora reprehenderit accusamus autem in omnis hic commodi, deleniti, atque doloribus quas ab libero molestiae! Molestias, dolorum nemo facere vero fugiat nesciunt itaque doloribus possimus nobis ducimus rem perspiciatis voluptates cum at repellat deleniti corrupti aliquam magnam laborum, ratione asperiores unde dolor non earum. Dolorum ab inventore ducimus possimus vero debitis sunt iusto natus alias excepturi provident, expedita facilis voluptate quibusdam, qui, architecto harum. Voluptatum inventore corrupti similique cumque nihil dolorum eum voluptatem quos labore possimus deserunt suscipit, numquam quibusdam, accusantium consequatur molestias ad sint aliquid recusandae expedita, molestiae in dolores? Facere vitae error qui saepe repellat eius laudantium! Omnis dolorem asperiores minima quae nulla. Neque tempore ipsa exercitationem quibusdam officiis assumenda delectus, accusamus deleniti animi quaerat nemo vitae placeat laborum architecto earum error fuga dolorum harum? Exercitationem distinctio sapiente, pariatur qui amet alias sunt sed quo quidem quos, suscipit dolore placeat? Rerum, alias. Suscipit possimus ab dignissimos minima est praesentium, voluptate saepe totam non molestias eaque mollitia, officia delectus sint. Tenetur debitis vel autem deleniti fuga eligendi blanditiis, minima natus. Molestiae debitis odio ad facilis veritatis. Dolore quo quod qui quasi suscipit, iure esse consectetur veritatis nemo quae doloribus!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem error sequi rem accusamus quae? Minima, laboriosam, perspiciatis obcaecati deleniti in dolore beatae unde enim soluta officia quidem voluptatum illo, blanditiis ratione qui! Cupiditate velit hic pariatur veniam fuga sequi corporis sunt aspernatur. Enim accusantium libero earum exercitationem facilis, unde fugiat mollitia cum reprehenderit qui, eveniet dolores voluptatum! Quae laborum inventore amet! Quidem fuga, neque voluptates amet iste non sapiente assumenda error, doloremque asperiores voluptatibus maxime ex magnam ab consectetur debitis id velit ipsa minima nihil, facilis quia optio. Laudantium soluta perferendis laborum ipsa debitis aliquid illo error consequuntur recusandae itaque, eveniet molestias eligendi culpa iure quam dolores architecto? Repudiandae iure tempora reprehenderit accusamus autem in omnis hic commodi, deleniti, atque doloribus quas ab libero molestiae! Molestias, dolorum nemo facere vero fugiat nesciunt itaque doloribus possimus nobis ducimus rem perspiciatis voluptates cum at repellat deleniti corrupti aliquam magnam laborum, ratione asperiores unde dolor non earum. Dolorum ab inventore ducimus possimus vero debitis sunt iusto natus alias excepturi provident, expedita facilis voluptate quibusdam, qui, architecto harum. Voluptatum inventore corrupti similique cumque nihil dolorum eum voluptatem quos labore possimus deserunt suscipit, numquam quibusdam, accusantium consequatur molestias ad sint aliquid recusandae expedita, molestiae in dolores? Facere vitae error qui saepe repellat eius laudantium! Omnis dolorem asperiores minima quae nulla. Neque tempore ipsa exercitationem quibusdam officiis assumenda delectus, accusamus deleniti animi quaerat nemo vitae placeat laborum architecto earum error fuga dolorum harum? Exercitationem distinctio sapiente, pariatur qui amet alias sunt sed quo quidem quos, suscipit dolore placeat? Rerum, alias. Suscipit possimus ab dignissimos minima est praesentium, voluptate saepe totam non molestias eaque mollitia, officia delectus sint. Tenetur debitis vel autem deleniti fuga eligendi blanditiis, minima natus. Molestiae debitis odio ad facilis veritatis. Dolore quo quod qui quasi suscipit, iure esse consectetur veritatis nemo quae doloribus!</p>
        </div>
    );
};

export default Dashboard;